config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :buildings, only: :index
  resources :users
  resources :equipments, only: :index
  resources :attacks, only: :index
  resources :towers, only: :index
  resources :alliances, only: :index
  resources :units, only: :index
  resources :tools, only: :index

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/equip_params.rb
class EquipParams < ActiveRecord::Base
  # belongs_to :equipment

  # enum accessory: [:commander, :castellan]
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  # has_many :equip_params
  # PARAMS_COMMANDER = %w{ hands arrows wall gate moat speed costs damage destroy glory detect honor resources }
  # PARAMS_CASTELLAN = %w{ hands arrows wall gate moat speed damage glory detect resources occupation }

  enum class: [:epic, :legendary, :unique]
  enum accessory: [:commander, :castellan]
  enum kind: [:armor, :weapon, :helmet, :artifact]
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  enum kind: [:melee, :ranged]
  # scope :visibility, -> (visibility) { where('show_link = ?', visibility) }

  # scope :server, -> (server) { where('server_id = ?', server) }
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :server

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.email = auth.info.email
      user.link = 'fb.com/' << auth.extra.raw_info.id
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    end
  end

  scope :visibility, -> (visibility) { where('show_link = ?', visibility) }

  scope :server, -> (server) { where('server_id = ?', server) }
end

app/controllers/alliances_controller.rb
class AlliancesController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :require_user

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
    redirect_to root_path
  end
  helper_method :current_user

  def require_user
    return if current_user
    redirect_to root_path, alert: 'Log in to view this page'
  end
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
  def index
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :set_equipment, only: [:edit, :show, :update, :destroy]

  def index
    # @equipment = Equipment.new
    # @equipments = Equipment.all
  end

  def new
  end

  def create
    @equipment = Eqipment.new(eqipment_params)
    render :new unless @equipment.save
  end

  def show
  end

  def edit
  end

  def update
    render :edit unless @equipment.update(equipment_params)
  end

  def destroy
    @equipment.destroy
  end

  private

  def equipment_params
    params.require(:eqipment).permit!
  end

  def set_equipment
    @equipment = Equipment.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:create]

  def create
    authenticate(request.env['omniauth.auth'])
    redirect_to user_path(session[:user_id])
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def authenticate(auth)
    user = User.find_by_uid(auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController
  def index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy]

  def index
    if current_user.server.id
      @users = User.all.visibility(true).server(current_user.server.id)
    end
  end

  def show
  end

  def update
    render :edit unless @user.update(user_params)
  end

  def destroy
    @user.destroy
    # TODO: show error notification
  end

  private

  def set_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit!
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_user

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def unknown(value)
    (value == '???' || value == true) ? 'unknown' : ''
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/alliances/index.html.slim
h2 Alliances

h4 Comming soon...

h4 At this page you'll see all alliances and info about, their users, etc.

app/views/application/_footer.html.slim
footer.page-footer
  .container
    .row
      .col.l6.s12
        h5.white-text Empire 4 Kingdoms
      .col.l4.offset-l2.s12
        h5.white-textLink
  .footer-copyright
    .container
      c 2015 kostyaha All right reserved.

app/views/application/_left_menu.html.slim
/* - if current_user */
.collection
  = link_to 'Users', users_path, class: 'collection-item'
  = link_to 'Alliances', alliances_path, class: 'collection-item'
  = link_to 'Towers', towers_path, class: 'collection-item'
  = link_to 'Equipments', equipments_path, class: 'collection-item'
  = link_to 'Attack', attacks_path, class: 'collection-item'
  = link_to 'Units', units_path, class: 'collection-item'
  = link_to 'Tools', tools_path, class: 'collection-item'
  = link_to 'Buildings', buildings_path, class: 'collection-item'

app/views/application/_right_block.html.slim
.right-wrapper
  - if Rails.env == 'production'
    .donate
      p= t('donate.title')
      p= t('donate.please')
    .commes
      script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
      /! test
      ins.adsbygoogle data-ad-client="ca-pub-1356023867752617" data-ad-format="auto" data-ad-slot="9792570681" style="display:block"
      javascript:
        (adsbygoogle = window.adsbygoogle || []).push({});

app/views/application/_top_menu.html.slim
nav.row
  .top_menu class='col s10 offset-s1'
    .nav-wrapper
      = link_to root_path do
        = image_tag 'logo.png'
      - if current_user
        ul id='nav-mobile' class='current_user right valign-wrapper'
          li= link_to current_user.name, user_path(current_user.id), class: 'waves-effect waves-teal btn-flat'
          li= link_to user_path(current_user.id) do
            = image_tag current_user.image
          = link_to 'Log Out', logout_path, class: 'waves-effect waves-light btn'

app/views/attacks/index.html.slim
h2 Attacks

h4 Comming soon...

h4 At this page you'll can calculate attacks or defence, forecast loss.

app/views/buildings/index.html.slim
- if params[:name]
  h4
    = link_to t('building.title'), buildings_path
    = ' / '
    = t("buildings.#{params[:name]}.name")
  table
    - t("buildings.#{params[:name]}.levels").each do |l|
      tr
        td.b-image rowspan=(6)
          = image_tag "buildings/#{l[1][:image]}", class: 'building-list'
        td.bottom_border= t('building.start_level') + ': '
        td.bottom_border class=unknown(l[1][:start_level]) = l[1][:legendary] == '1' ? t('building.from_leg_level', level: l[1][:start_level]) : t('building.from_level', level: l[1][:start_level] )
      tr
        td.bottom_border= t("buildings.#{params[:name]}")[:parametr] + ': '
        td.bottom_border class=unknown(l[1][:value]) = l[1][:value]
      tr
        td.bottom_border= t('building.expirience') + ': '
        td.bottom_border class=unknown(l[1][:expirience]) = l[1][:expirience]
      tr
        td.bottom_border= t('building.order') + ': '
        td.bottom_border class=unknown(l[1][:order]) = l[1][:order]
      tr
        td.bottom_border= t('building.architect.title') + ': '
        td.bottom_border class=unknown(l[1][:architect])
          - if l[1][:architect] == '???'
            = '???'
          - else
            = l[1][:architect] == '1' ? t('building.architect.need') : t('building.architect.no_need')
      tr
        td= t('cost') + ': '
        td class=unknown(l[1][:cost].include? '???')
          - if l[1][:cost].split(',')[0] != '0'
            p.no-margin= t('wood') + ': ' + l[1][:cost].split(',')[0]
          - if l[1][:cost].split(',')[1] != '0'
            p.no-margin= t('stone') + ': ' + l[1][:cost].split(',')[1]
          - if l[1][:cost].split(',')[2] != '0'
            p.no-margin= t('iron') + ': ' + l[1][:cost].split(',')[2]
          - if l[1][:cost].split(',')[3] != '0'
            p.no-margin= t('charcoal') + ': ' + l[1][:cost].split(',')[3]
          - if l[1][:cost].split(',')[4] != '0'
            p.no-margin= t('olive') + ': ' + l[1][:cost].split(',')[4]
          - if l[1][:cost].split(',')[5] != '0'
            p.no-margin= t('glass') + ': ' + l[1][:cost].split(',')[5]
          - if l[1][:cost].split(',')[6] != '0'
            p.no-margin= t('rubies') + ': ' + l[1][:cost].split(',')[6]
      tr
        td.blank colspan=(3)


- else
  table.bordered

    - I18n.t('buildings').each do |b|
      .col.s6.m4
        .card
          .card-image
            = image_tag "buildings/#{b[0]}.jpg"
          .card-content
            p.card-title = link_to b[1][:name], buildings_path(name: b[0])
            p= b[1][:description]

app/views/equipments/_equipment.html.slim
   .row
        .col.s12.m6
          .card.blue-grey.darken-1
            .card-content.white-text
              p= @equipment.class
              p= @equipment.accessory
              p= @equipment.kind
              p= @equipment.level
              p= "#{@equipment.param1.value} #{@equipment.param1.name}"

            .card-action
              =link_to 'Destroy',
              <a href="#This is a link</a>
              <a href="#This is a link</a>

app/views/equipments/_form.html.slim
- binding.pry
= simple_form_for @equipment do |f|
  .row
    .col.s12.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          p= @equipment.class
          p= @equipment.accessory
          p= @equipment.kind
          p= @equipment.level
          p= "#{@equipment.param1.value} #{@equipment.param1.name}"

.card-action
  =link_to 'Destroy', equipment_path(@equipment), class: 'waves-effect waves-light btn'
    'Delete'
    i.material-icons.right delete

app/views/equipments/index.html.slim
h2 Equipments

h4 Comming soon...

h4 At this page you'll can collect all your equipments, dress your generals and governors.


/* = render 'form' */

/* = render @equipments */

app/views/tools/index.html.slim
h2= t('tool.title')

/* - binding.pry */

- I18n.t('tools').each do |tool|
  .col.s6.m4
    .card
      .card-image.waves-effect.waves-block.waves-light
        = image_tag "tools/#{tool[0]}.jpg", class: 'activator'
      .card-content
        span.card-title.activator.grey-text.text-darken-4
          = tool[1][:name]
      .card-reveal
        span.card-title.grey-text.text-darken-4
          = tool[1][:name]
          i.material-icons.right close
        p= tool[1][:defof] == '1' ? t('tool.of') : t('tool.def')
        p= tool[1][:description]
        p= "#{tool[1][:parameter]}: #{tool[1][:value]}"
        p= "#{t('tool.speed')}: #{tool[1][:speed]}"
        - if tool[1][:cost].split(',')[0] != '0'
          p.no-margin= t('wood') + ': ' + tool[1][:cost].split(',')[0]
        - if tool[1][:cost].split(',')[0] != '0'
          p.no-margin= t('wood') + ': ' + tool[1][:cost].split(',')[0]
        - if tool[1][:cost].split(',')[0] != '0'
          p.no-margin= t('wood') + ': ' + tool[1][:cost].split(',')[0]
        - if tool[1][:cost].split(',')[0] != '0'
          p.no-margin= t('wood') + ': ' + tool[1][:cost].split(',')[0]

app/views/towers/index.html.slim
h2 Towers

h4 Comming soon...

h4 At this page you'll see all tower barons, their defence and other info.

app/views/units/_unit.html.slim
tr
  td.picture= cl_image_tag("units/#{unit.image}", :width => 60, :height => 50)
  td= unit.name
  td= unit.power
  td= unit.defmelee
  td= unit.defranged
  td= unit.capasity
  td= unit.speed
  td= unit.food

app/views/units/index.html.slim
h2= t('unit.title')

/* - binding.pry */

- I18n.t('units').each do |unit|
  .col.s6.m4
    .card
      .card-image.waves-effect.waves-block.waves-light
        = image_tag "units/#{unit[0]}.jpg", class: 'activator'
      .card-content
        span.card-title.activator.grey-text.text-darken-4
          = unit[1][:name]
      .card-reveal
        span.card-title.grey-text.text-darken-4
          = unit[1][:name]
          i.material-icons.right close
        p= "#{unit[1][:kind] == 1 ? t('unit.strength_melee') : t('unit.strength_ranged')}: #{unit[1][:strength]}"
        p= "#{t('unit.def_melee')}: #{unit[1][:def_melee]}"
        p= "#{t('unit.def_ranged')}: #{unit[1][:def_ranged]}"
        p= "#{t('unit.capasity')}: #{unit[1][:capasity]}"
        p= "#{t('unit.speed')}: #{unit[1][:speed]}"
        p= "#{t('unit.food')}: #{unit[1][:food]}"

app/views/users/index.html.slim
- if current_user.show_link?
  h4 User who want share with gifts: #{@users.count}
  br
  .collection.row
    - @users.each do |user|
      => link_to "http://#{user.link}", target: '_blank', class: 'collection-item ' do
        .nickname= user.nickname
        .username= user.name

app/views/users/show.html.slim
h4= t('user.profile')
br

- if current_user
  .row
    .user_form.col.m6
      = simple_form_for @user, remote: true do |f|
        = f.label 'My nickname in game'
        = f.input :nickname, label: false
        br
        = f.label 'Your server'
        = f.association :server, collection: Server.all.order(:name), label: false
        br
        = f.label 'X coordinate at Great Empire'
        = f.input :x, label: false
        = f.label 'Y coordinate at Great Empire'
        = f.input :y, label: false
        = f.input :show_link, label: 'Other users can see link to my Facebook account'
        br
        = f.submit t('form.save'), class: 'waves-effect waves-light btn'
    .col.m6
      = image_tag current_user.image
      p= current_user.name
      p= current_user.link
      p= current_user.email

app/views/welcome/index.html.slim
h2 Welcome
= link_to 'Login with Facebook', '/auth/facebook'